### ISSUE TITLE
Video play fails even though uploader reports video is ready

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#189] opened 2018-02-20 07:45 UTC
Even when the UI shows a video as being ready to play, it is not necessarily ready:

![image](https://user-images.githubusercontent.com/7697924/36412381-fa7c5e0c-15e7-11e8-81df-35e8e3ce4be2.png)

In my testing, it is possible to have the UI report a video is ready when it does not have an `ipfsHash`. This causes video playing to fail in `Clappr` w/ a runtime error.

Additionally, the UI will not report that a video is ready to play until a title is entered. Is this intended?

**Comment by jellegerbrandy** [comment] 2018-02-20 17:41
Perhaps the ipfsHash issue is related to the state management as well:l https://github.com/Paratii-Video/paratii-portal/issues/186

About the "ready to play" issue: yes, this is intended, but it a part of the UX we may reconsider.

**Comment by jellegerbrandy** [comment] 2018-02-22 14:14
Closing this, as this logic has changed. If we still have an issue like this, we can create a new one (with a description of how to reproduce :-))

**Closed by jellegerbrandy** 2018-02-22 14:14 UTC
