### ISSUE TITLE
Devise mechanism for differentiating between dev/test and prod

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#27] opened 2017-12-28 14:06 UTC
There will be some configuration/functionality that needs to differ locally vs on production. This includes how we connect to the registry via `paratt-lib`, the registry address to connect to, and possibly other things we haven’t thought of yet. We should come up with a consistent approach to make this differentiation. I think [weback’s define plugin](https://webpack.js.org/plugins/define-plugin/) might be the way to go.

**Comment by jellegerbrandy** [comment] 2018-01-09 09:56
This is a duplicate of #41

**Closed by jellegerbrandy** 2018-01-09 09:56 UTC
