### ISSUE TITLE
tipping tweaks

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#765] opened 2018-07-05 07:59 UTC
* It seems that the tipping options do not appear if you are not signed in. Is that by design?

*We should close this message by clicking everywhere ( there's no other option to click)

![image](https://user-images.githubusercontent.com/1306173/42309683-9a121a04-8039-11e8-8c8e-ce0dd1f88474.png)

* the "give a tip" pops up also during the process of tipping (i.e. while it asks me for my pass)

**Comment by jellegerbrandy** [comment] 2018-07-05 11:05
Original issue with the design is #684

**Comment by pedrocasa** [comment] 2018-07-05 18:58
"It seems that the tipping options do not appear if you are not signed in. Is that by design?" 

yes, otherwise we would need to face the nightmare to make a login flow inside the player or pop up a modal to sign up/sign in the portal

**Comment by pedrocasa** [comment] 2018-07-05 19:31
"It ssems that the tipping options does not appear if you are not signed in. Is that by design?" 

In the original design yes, we can make the tipping button a trigger for the sign in/sign up process ( it can work since there is no need to create a login flow inside the player)

**Comment by bent0b0x** [comment] 2018-07-05 21:43
>It seems that the tipping options do not appear if you are not signed in. Is that by design?

I believe this was unintentional, mistake by me. It was written to be a trigger for sign-in. Let me fix

**Comment by bent0b0x** [comment] 2018-07-05 22:16
Both of these issues are resolved in #767

**Closed** 2018-07-06 12:15 UTC
