### ISSUE TITLE
Paratii-embed always autoplaying

### ISSUE THREAD

**Issue by jrgarou** [Paratii-Video/paratii-portal#382] opened 2018-03-21 13:40 UTC
The  `autoplay=0` from `paratii-embed` it always play the video: https://jsfiddle.net/garou/yvndabg8/

`<iframe webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true" src="https://portal.paratii.video/embed/akX1Cvz1G7In?autoplay=0&loop=1&playsinline=1&fullscreen=1&type=mini" width="570" height="320" frameborder="0"></iframe>`

**Comment by bent0b0x** [comment] 2018-04-09 11:06
@felipegaucho I should be able to do this one tonight but @geckoslair feel free to take it first

**Comment by geckoslair** [comment] 2018-04-09 12:11
the issue is on components/Play.js at line 529

`this.player = CreatePlayer({
        selector: `#${PLAYER_ID}`,
        source: `https://gateway.paratii.video/ipfs/${
          video.ipfsHash
        }/master.m3u8`,
        poster: `https://gateway.paratii.video/ipfs/${
          video.ipfsHash
        }/${poster}`,
        mimeType: 'application/x-mpegURL',
        ipfsHash: video.ipfsHash,
        autoPlay: true
      })`

where the player is forced to be always in autoplay. @bent0b0x what is the right way to get the query parameters and set in player instance accordingly ? I'd like to do that but i need some hints from you =)

**Comment by bent0b0x** [comment] 2018-04-09 13:04
React router used to include url query parsing, but I think we’ll just need to find an npm package that does it for us since v4 has dropped that support. So we’ll just parse the query and use that to say whether or not we should autoplay

**Comment by jrgarou** [comment] 2018-04-09 14:30
@bent0b0x @felipegaucho @geckoslair 
We could set up `autoPlay: this.props.isEmbed ? false : true` for now.
What do you think?

**Comment by jrgarou** [comment] 2018-04-09 14:43
good to know @bent0b0x

There's an issue on that,  Quality control starts with "auto" option only until playing a video.

![image](https://user-images.githubusercontent.com/320157/38504316-c042dc1a-3bea-11e8-8ad0-54889f8dcf14.png)

**Comment by bent0b0x** [comment] 2018-04-09 14:45
@jrgarou how is that related to this issue? Can you open up a separate issue for that? 

This will require some design input from @pedrocasa; the video does not immediately give us all of the available video qualities. Clappr fetches them asynchronously. So we'll need an intermediate state until we get all of them (or we can just leave as is).

**Comment by jrgarou** [comment] 2018-04-09 15:01
@bent0b0x Yes I can. Just pointing first
So we don't need to handle [this](https://github.com/Paratii-Video/paratii-portal/issues/382#issuecomment-379776784) if we set up a start state(perhaps a big play button).

**Comment by bent0b0x** [comment] 2018-04-09 15:03
Gotcha, makes sense!

**Comment by felipegaucho** [comment] 2018-04-13 06:56
Closing this assuming the "big play button" https://github.com/Paratii-Video/paratii-portal/issues/449 will solve it, as per @jrgarou 
(interesting that clappr fetches these folks asynchronously..)

**Closed by felipegaucho** 2018-04-13 06:56 UTC
Labels: bug, embed
